### ISSUE TITLE
Pairings seem to be strictly top-down instead of randomized

### ISSUE THREAD

**Issue by gereons** [MrHuds0n/golden#14]
Starting from the same partial tournament result I posted in #13, pairing the 3rd round always results in these pairings: G+F, f+M, A+J, P+K, R+N, T+S. 

I would expect the pairings on the lower tables to sometimes be different, e.g. P+R, T+N, K+S, because of the random shuffling that should occur before picking players from their match point groups.

**Comment by zanlib0** [comment]
This seems to be because the players are first sorted by order of Points → SOS → ESOS. I thought that was the correct and fair way to pair up players but now that I read the tournament regulations I think this might be incorrect.

As far as I understand, the SOS and ESOS rankings should be only taken into account during calculating the cut, right? If this is right then the next commit will have this issue sorted out.

**Comment by gereons** [comment]
That's correct: SoS/eSoS only play a role when determining final rankings, not when pairing in Swiss.

**Comment by zanlib0** [comment]
Great.
